### ISSUE TITLE
Documentation or Setup instruction request 

### ISSUE THREAD

**Issue by Kirito70** [Dealerpriest/robbit#10]
Hi, I am trying to deploy this project on an AWS server. But I am facing this issue 

`the file turnserver.conf not found. Please provide one so we can setup COTURN correctly. Have a look at example.turnserver.conf for reference`

I have created that file from scratch as example.turnserver.conf file is not available. So I have just copied variables from .env.

If you can please provide us with initial documentation that would be great. Can you please provide us all of the steps that are required to make this work?

**Comment by Dealerpriest** [comment]
Actually I have changed the code so that the file "turnserver.conf" is no longer used. Instead I have changed the docker-compose file so that the COTURN container receives the settings directly as env variables. Have a look [here](https://github.com/Dealerpriest/robbit/blob/2bb19552c47be707e589d261dddf3ab8fadc3c7e/backend/docker/docker-compose.yml#L21). I forgot to remove the check in the `run-everything.sh` script as I usually don't use that script but rather just call `docker-compose up --build` directly. I will fix this ASAP.
